name: Job Scraper

on:
  schedule:
    # Runs every hour at :05 past the hour
    - cron: '5 * * * *'
  
  # Allows manual triggering from GitHub UI
  workflow_dispatch:

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          pip install requests python-dotenv
      
      - name: Download previous tracker
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: sent-jobs-tracker
      
      - name: Run job scraper
        env:
          JOB_WEBHOOK_URL: ${{ secrets.JOB_WEBHOOK_URL }}
        run: |
          python job_scraper.py
      
      - name: Upload sent jobs tracker
        uses: actions/upload-artifact@v4
        with:
          name: sent-jobs-tracker
          path: sent_jobs.json
          retention-days: 90

